config/routes.rb
Rails.application.routes.draw do

  # top-page
  root 'static_pages#top'

  # login/logout
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Messaging-API
  post '/callback', to: 'webhooks#callback'

  resources :users do
    resources :questions
    resources :challenges
    post 'challenges/ajax_update', to: 'challenges#ajax_update'
    patch 'challenges/update_proficiency', to: 'challenges#update_proficiency'
  end

  # get    '/layout', to: 'sessions#show'
  get    '/selfpr', to: 'sessions#show'

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  validates :question, presence: true, length: { maximum: 200 }
  validates :correct, presence: true, length: { maximum: 5000 }
  validates :proficiency, presence: true, numericality: {greater_than: 0,less_than: 4}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :new, :edit]
  before_action :correct_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :set_questions, only: :index
  before_action :admin_user_reject, only: [:index, :new, :edit]

  def new
    @question = Question.new
  end

  def index
  end

  def create
    @question = Question.new(question_params)
    #@question = Question.new(question: params[:question][:question], correct: params[:question][:correct])
    @question.user_id = @user.id
    #@question.proficiency = 1
    if @question.save
      flash[:success] = "問題を新規作成しました。"
      redirect_to user_questions_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      flash[:success] = "内容を更新しました。"
      redirect_to user_questions_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    flash[:success] = "「問題ID: #{@question.id}」を削除しました。"
    user_questions_count = @user.questions.count
    if user_questions_count == 0
      redirect_to user_questions_path
    else
      referer_url = request.referer
      if referer_url.include?("?page=")
        redirect_url_base = referer_url.split('?page=').first
        last_page_number = referer_url.split('=').last
        redirect_page_number = user_questions_count % PAGE_NUMBER == 0 ? last_page_number.to_i - 1 : last_page_number
        redirect_url = "#{redirect_url_base}?page=#{redirect_page_number}"
      else
        redirect_url = referer_url
      end
      redirect_to "#{redirect_url}"
    end
      
  end

  private
    def question_params
      params.require(:question).permit(:question, :correct, :proficiency)
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<div class="height-change-line"></div>
<div class="jumbotron jumbotron-none jumbotron-long">
  <div class="row form-row-common">
    <div class="col-md-6 col-md-offset-3 form-content">
    <h1 class="headline page-title"><%= yield(:page_title) %></h1>
      <%= form_with(model:[@user, @question], local: true) do |f| %>
      <%= render 'shared/error_messages', object: @question %>

        <div class="form-content-common form-content-top">
          <label class="form-label-common">問題</label>
          <%= f.text_area :question, rows: 5, class: "form-control" %>
        </div>

        <div class="form-content-common">
          <label class="form-label-common">正解</label>
          <%= f.text_area :correct, rows: 5, class: "form-control" %>
        </div>

        <div class="form-content-common">
          <label class="form-label-common">習熟度</label>
          <%= f.text_field :proficiency, class: "form-control" %>
        </div>
                
        <div class="form-content-common">
          <div class="button-group">
            <a class="btn-content bs-lg cubic">
              <span class="hovering"><%= f.submit yield(:button_text), class: "submit-layout a-side" %></span>
              <span class="default"><%= f.submit yield(:button_text), class: "submit-layout b-side" %></span>
            </a>
          </div>
        </div>
        <% if controller.action_name == "edit" || controller.action_name == "update" %>
          <%= link_to "キャンセル", user_questions_path(@user.id), class: "btn btn-md btn-danger" %>
        <% end %>

      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<% provide(:title, "Question-Edit") %>
<% provide(:page_title, "Question Edit page") %>
<% provide(:button_text, '更新') %>
<%= render 'form' %>

app/views/questions/index.html.erb
<% provide(:title, "Question index") %>
<% provide(:page_title, "Question Index page") %>

<div class="height-change-line"></div>
<div class="jumbotron jumbotron-none jumbotron-long">
  <div class="container">
    <div class="row form-row-common">
      <h1 class="headline headline__mt page-title"><%= yield(:page_title) %></h1>
      <%= render 'shared/flash_messages' %>

      <div class="willpaginate-button-top" data-turbolinks="false"><%= will_paginate %></div>
      <table class="table table-bordered table-striped table-common">
        <thead class="table-column">
          <tr>
            <th class="col-1 align-middle text-center">ID</th>
            <th class="col-3 align-middle text-center">問題</th>
            <th class="col-5 align-middle text-center">正解</th>
            <th class="col-1 align-middle text-center">習熟度</th>
            <th class="col-1 align-middle text-center"></th>
          </tr>
        </thead>

        <tbody>
          <% @questions.each do |quest| %>
            <tr>
            <td class="align-middle text-center"><%= quest.id %></td>
            <td><%= simple_format(h(quest.question)) %></td>
            <td><%= simple_format(h(quest.correct)) %></td>
            <td class="align-middle text-center"><%= quest.proficiency %></td>
            <td class="text-center align-middle">
              <%= link_to "編集", edit_user_question_path(@user, quest.id), class: "btn btn-edit" %>
              <%= link_to "削除", user_question_path(@user, quest.id), method: :delete, data: { confirm: "「問題ID: #{quest.id}」を削除します。よろしいですか？"}, class: "btn btn-delete" %>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div  data-turbolinks="false"><%= will_paginate %></div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<% provide(:title, "Question-New") %>
<% provide(:page_title, "Question Create page") %>
<% provide(:button_text, '新規登録') %>
<%= render 'form' %>