config/routes.rb
Rails.application.routes.draw do

  # top-page
  root 'static_pages#top'

  # login/logout
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Messaging-API
  post '/callback', to: 'webhooks#callback'

  resources :users do
    resources :questions
    resources :challenges
    post 'challenges/ajax_update', to: 'challenges#ajax_update'
    patch 'challenges/update_proficiency', to: 'challenges#update_proficiency'
  end

  # get    '/layout', to: 'sessions#show'
  get    '/selfpr', to: 'sessions#show'

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_user, only: [:new, :update, :ajax_update]
  before_action :logged_in_user, only: :new
  before_action :correct_user, only: :new
  before_action :admin_user_reject, only: :new


  def new
    if @user.questions.count >= 1
      id_array = @user.questions.pluck(:id)
      rand_question_id = id_array.sample(1).first
      answering_user = @user.answerings.first
      if @user.questions.count != 1
        while rand_question_id == answering_user.answering_id do
          rand_question_id = id_array.sample(1).first
        end
        @question = Question.find(rand_question_id)
        answering_user.answering_id = rand_question_id
        answering_user.save
        else
      @question = Question.find(rand_question_id)
      answering_user.answering_id = rand_question_id
      answering_user.save
      end
    else
      flash[:danger] = '問題が登録されていません。'
      redirect_to user_questions_path
    end
  end

  def update
    proficiency = params[:value].to_i
    question = Question.find(@user.answerings.first.answering_id)
    unless question.proficiency == proficiency
      question.proficiency = proficiency
      question.save
      flash[:success] = '習熟度を変更しました。'
    end
    redirect_to new_user_challenge_path
  end
  
  def ajax_update
    @text = Question.find(@user.answerings.first.answering_id).correct
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/ajax_update.js.erb
// 「content」に@textの内容を代入する。
var content = '<%= "#{ @text }" %>'

if(!(content.match(/\r\n/g))) {
    $('#ajax-test').text(content)
    $('#ajax-test').text(content)
    $('#ajax-test').text(content)
} else {
    let result = content.replace(/\r\n/g, "<br>")
    $('#ajax-test').text(`${result}`)
}

//let result = content.match(/\r\n/g)
let result = content.replace(/\r\n/g, "<br>")
let aaa = content.match(/\r\n/g)
//$('#ajax-test').text(`${aaa}`)


//if(Boolean(result) === nill) {
//    $('#ajax-test').text('aaa')
//}

//if(content.match(/\r\n/g)) {
//    $('#ajax-test').text('改行あり');
//}

//「id="ajax-test"」にcontentで書かれた内容を反映

//$('#ajax-test').text(`${result}`);



//$('#ajax-test').text(content);

app/views/challenges/new.html.erb
<% provide(:title, 'Challenge') %>
<% provide(:page_title, "Challenge page") %>

<div class="height-change-line"></div>
<div class="jumbotron jumbotron-none jumbotron-long">
  <div class="container">
    <h1 class="headline page-title"><%= yield(:page_title) %></h1>
    <%= render 'shared/error_messages', object: @user %>
    <%= render 'shared/flash_messages' %>

  <div class="row challenge-form-top">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-header challenge-question">
          <%= "問題ID: #{@question.id}"%>
        </div>
        <div class="card-body d-flex align-items-center justify-content-center">
          <div><h5 class="card-title"><%= simple_format(h(@question.question)) %></h5></div>
        </div>
      </div>

      <div class="other-question-parent">
        <input type="button" value="他の問題" class="btn-other-question" onclick="window.location.reload(true);" />
      </div>

      <div class="input-group challenge-margin">
        <div class="input-group-prepend">
          <span class="input-group-text challenge-input">回答入力欄</span>
        </div>
        <textarea class="form-control" aria-label="With textarea" rows="7"></textarea>
      </div>

      <button class="correct-button" onclick="document.querySelector('.correct-form').classList.toggle('correct-view');"><span>答えを表示する</span>答えを表示する</button>

    </div>


    <div class="col-lg-6">
      <div class="correct-form">
        <div class="correct-title">正解</div>
        <div class="correct-view-base">
          <textarea class="correct-view-area" rows="12"><%= (@question.correct) %></textarea>
        </div>
      </div>
    </div>

    <div class="col-lg-6 offset-lg-3">
      <%= form_with(url: user_challenges_update_proficiency_path, method: :patch, local: true) do |f| %>
        <div class="proficiency-aria-parent">
          <div class="proficiency-title">習熟度の設定</div>
          <div class="proficiency-aria">
            <%= f.radio_button :value, 1, class: "lavel-1", checked: bool = @question.proficiency == 1 ? true : false %>
            <%= f.radio_button :value, 2, class: "lavel-2", checked: bool = @question.proficiency == 2 ? true : false %>
            <%= f.radio_button :value, 3, class: "lavel-3", checked: bool = @question.proficiency == 3 ? true : false %>
          </div>
        </div>
        <div>
          <%= f.submit "次の問題", class: "btn btn-primary btn-block btn-next-question" %>
        </div>
      <% end %>
    </div>

    <div class="col-lg-6">
    </div>

  </div>
</div>