config/routes.rb
Rails.application.routes.draw do

  # top-page
  root 'static_pages#top'

  # login/logout
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Messaging-API
  post '/callback', to: 'webhooks#callback'

  resources :users do
    resources :questions
    resources :challenges
    post 'challenges/ajax_update', to: 'challenges#ajax_update'
    patch 'challenges/update_proficiency', to: 'challenges#update_proficiency'
  end

  # get    '/layout', to: 'sessions#show'
  get    '/selfpr', to: 'sessions#show'

end

app/views/layouts/_header.html.erb
<% unless controller_name == "sessions" && controller.action_name == "show" %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a><%= link_to "AgainstFc", root_path, class: "navbar-brand" %></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if logged_in? %>
      <% unless @current_user.admin? %>
        <% provide(:class_fication, user_questions_path(@current_user)) %>
      <% else %>
        <% provide(:class_fication, users_path) %>
      <% end %>
    <% else %>
      <% provide(:class_fication, root_path) %>
    <% end %>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "Home", yield(:class_fication), class: "nav-link" %></li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a><%= link_to "アカウント編集", edit_user_path(@current_user), class: "dropdown-item" %></a>
              <% if @current_user.admin? %>
                <a><%= link_to "ユーザ一覧画面", yield(:class_fication), class: "dropdown-item" %></a>
              <% end %>
            </div>
          </li>
          <% unless @current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Question
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a><%= link_to "問題登録", new_user_question_path(current_user), class: "dropdown-item" %></a>
                <a><%= link_to "問題一覧画面", user_questions_path(current_user), class: "dropdown-item" %></a>
                <a><%= link_to "チャレンジ画面", new_user_challenge_path(current_user), class: "dropdown-item" %></a>
              </div>
            </li>
          <% end %>
          <li><%= link_to "Logout", logout_path, method: :delete, data: { confirm: "ログアウトします。よろしいですか？"}, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
<%
=begin%>
  <div class="container"><%= debug(params) if Rails.env.development? %></div>
<%
=end
%>
  </body>
</html>